os:
  - linux
language: android
jdk:
  - oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API=28
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=24.0.2
    - ADB_INSTALL_TIMEOUT=5 # minutes
cache:
  directories:
    - $HOME/.m2
before_install:
  - java -version
  - sleep 10
script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
